# yaml-language-server: $schema=./values.schema.json

replicas: 1
context_name: dev
server: https://myserver.example.com:6443

github:
  token: ""
  url: ""
  app_private_key_file: ""
  app_private_key: ""
  app_id: ""

metrics:
  port: 9090

service_monitor:
  enabled: false

podSecurityContext: {}
  #fsGroup: 2000

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false

nodeSelector: {}
tolerations: []
affinity: {}
