apiVersion: apps/v1
kind: Deployment
metadata:
  name: klum
  namespace: {{- .Values.namespace}}
spec:
  replicas: {{- .Values.replicas}}
  selector:
    matchLabels:
      run: klum
  template:
    metadata:
      labels:
        run: klum
    spec:
      serviceAccountName: klum
      containers:
        - image: "ghcr.io/jadolg/klum:{{- .Values.version}}"
          name: klum
          env:
            - name: CONTEXT_NAME
              value: {{- .Values.context_name}}
            - name: SERVER
              value: {{- .Values.server}}
            - name: NAMESPACE
              value: {{- .Values.namespace}}
