{{- if and .Values.github.app_private_key (not .Values.github.app_private_key_file) }}
apiVersion: v1
kind: Secret
metadata:
  name: klum-github-app-key-file
type: Opaque
data:
  github-app-private-key-file: {{ .Values.github.app_private_key | b64enc }}
{{- end }}
