{{- if .Values.github.app_private_key_file }}
apiVersion: v1
kind: Secret
metadata:
  name: klum-github-app-key-file
type: Opaque
data:
  github-app-private-key-file: {{ (.Files.Get .Values.github.app_private_key_file) | b64enc }}
{{- end }}
